---
- hosts: host
  become: yes
  roles:
    - Ossec
    - pytbull  
  tags:
    - Ossec
    - pytbull  
- hosts: server
  become: yes
  roles: 
    - pytbull
    - snort 
    - suricata
    - pulledpork
    - tools
  tags:
    - pulledpork
    - pytbully
    - snort 
    - suricata
    - tools