---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu_dev_ops
    dockerfile: ../common/Dockerfile.j2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
provisioner:
  name: ansible
  env: 
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_CONFIG: ../../ansible.cfg
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy